services:
  # Frontend Service
  - type: web
    name: vpn-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://vpn-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://vpn-backend.onrender.com

  # Backend Service
  - type: web
    name: vpn-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: FRONTEND_URL
        value: https://vpn-frontend.onrender.com 