/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VPNRegistry } from "./VPNRegistry";
export type { VPNSubscription } from "./VPNSubscription";
export * as factories from "./factories";
export { VPNRegistry__factory } from "./factories/VPNRegistry__factory";
export { VPNSubscription__factory } from "./factories/VPNSubscription__factory";
