/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VPNRegistry__factory } from "./VPNRegistry__factory";
export { VPNSubscription__factory } from "./VPNSubscription__factory";
